In [1]:
!pip install tensorflow

     -------------------------------------- 266.3/266.3 MB 1.0 MB/s eta 0:00:00
     -------------------------------------- 124.6/124.6 kB 3.7 MB/s eta 0:00:00
     ---------------------------------------- 14.2/14.2 MB 8.1 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 8.6 MB/s eta 0:00:00
     ---------------------------------------- 6.0/6.0 MB 9.6 MB/s eta 0:00:00
     -------------------------------------- 439.2/439.2 kB 6.9 MB/s eta 0:00:00
     ---------------------------------------- 1.7/1.7 MB 9.0 MB/s eta 0:00:00
     ---------------------------------------- 65.5/65.5 kB 3.5 MB/s eta 0:00:00
     ---------------------------------------- 57.5/57.5 kB 3.0 MB/s eta 0:00:00
     -------------------------------------- 895.9/895.9 kB 8.1 MB/s eta 0:00:00
     ---------------------------------------- 3.7/3.7 MB 9.5 MB/s eta 0:00:00
     -------------------------------------- 781.3/781.3 kB 7.0 MB/s eta 0:00:00
     -------------------------------------- 177.

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
import pandas as pd
import numpy as np

In [12]:
data_set = np.loadtxt('./deep_data/ThoraricSurgery.csv', delimiter=',')
data_set

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [13]:
x = data_set[:, 0:17]
y = data_set[:, 17]

In [15]:
x

array([[293.  ,   1.  ,   3.8 , ...,   1.  ,   0.  ,  62.  ],
       [  1.  ,   2.  ,   2.88, ...,   1.  ,   0.  ,  60.  ],
       [  8.  ,   2.  ,   3.19, ...,   1.  ,   0.  ,  66.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,   0.  ,  62.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,   0.  ,  58.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,   0.  ,  49.  ]])

In [16]:
y

array([0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0.

In [ ]:
# neural network 구성

# input_dim : 입력값의 차원
# 30 : hidden layer의 node의 갯수

In [14]:
model = Sequential()
model.add(Dense(30, input_dim=17, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 30)                540       
                                                                 
 dense_1 (Dense)             (None, 1)                 31        
                                                                 
Total params: 571
Trainable params: 571
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


In [ ]:
# neural network 학습
# epochs : 전체 데이터에 대해서 몇 번 학습시킬 것인지..
# batch_size : 네이워크에 10개의 데이터를 묶어서 묶음단위로 네트워크에 입렵

In [19]:
model.fit(x,y, epochs=100, batch_size=10)

Epoch 1/100
47/47 [==============================] - 1s 1ms/step - loss: 2.8855 - accuracy: 0.7447
Epoch 2/100
47/47 [==============================] - 0s 1ms/step - loss: 1.1732 - accuracy: 0.7532
Epoch 3/100
47/47 [==============================] - 0s 978us/step - loss: 0.8105 - accuracy: 0.7872
Epoch 4/100
47/47 [==============================] - 0s 999us/step - loss: 0.6211 - accuracy: 0.8128
Epoch 5/100
47/47 [==============================] - 0s 978us/step - loss: 0.5452 - accuracy: 0.8319
Epoch 6/100
47/47 [==============================] - 0s 1ms/step - loss: 0.5043 - accuracy: 0.8319
Epoch 7/100
47/47 [==============================] - 0s 1000us/step - loss: 0.4953 - accuracy: 0.8468
Epoch 8/100
47/47 [==============================] - 0s 1ms/step - loss: 0.5091 - accuracy: 0.8277
Epoch 9/100
47/47 [==============================] - 0s 1ms/step - loss: 0.4531 - accuracy: 0.8468
Epoch 10/100
47/47 [==============================] - 0s 999us/step - loss: 0.4585 - accuracy: 0.853

47/47 [==============================] - 0s 978us/step - loss: 0.4169 - accuracy: 0.8511
Epoch 83/100
47/47 [==============================] - 0s 1ms/step - loss: 0.3989 - accuracy: 0.8468
Epoch 84/100
47/47 [==============================] - 0s 934us/step - loss: 0.4142 - accuracy: 0.8489
Epoch 85/100
47/47 [==============================] - 0s 934us/step - loss: 0.4617 - accuracy: 0.8426
Epoch 86/100
47/47 [==============================] - 0s 1000us/step - loss: 0.4702 - accuracy: 0.8553
Epoch 87/100
47/47 [==============================] - 0s 1ms/step - loss: 0.4091 - accuracy: 0.8532
Epoch 88/100
47/47 [==============================] - 0s 1ms/step - loss: 0.4264 - accuracy: 0.8553
Epoch 89/100
47/47 [==============================] - 0s 999us/step - loss: 0.4284 - accuracy: 0.8489
Epoch 90/100
47/47 [==============================] - 0s 934us/step - loss: 0.3740 - accuracy: 0.8532
Epoch 91/100
47/47 [==============================] - 0s 978us/step - loss: 0.4152 - accuracy: 0.848